// Code generated by ent, DO NOT EDIT.

package mininggoodstock

import (
	"entgo.io/ent"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const (
	// Label holds the string label denoting the mininggoodstock type in the database.
	Label = "mining_good_stock"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldEntID holds the string denoting the ent_id field in the database.
	FieldEntID = "ent_id"
	// FieldGoodStockID holds the string denoting the good_stock_id field in the database.
	FieldGoodStockID = "good_stock_id"
	// FieldPoolRootUserID holds the string denoting the pool_root_user_id field in the database.
	FieldPoolRootUserID = "pool_root_user_id"
	// FieldPoolGoodUserID holds the string denoting the pool_good_user_id field in the database.
	FieldPoolGoodUserID = "pool_good_user_id"
	// FieldTotal holds the string denoting the total field in the database.
	FieldTotal = "total"
	// FieldSpotQuantity holds the string denoting the spot_quantity field in the database.
	FieldSpotQuantity = "spot_quantity"
	// FieldLocked holds the string denoting the locked field in the database.
	FieldLocked = "locked"
	// FieldInService holds the string denoting the in_service field in the database.
	FieldInService = "in_service"
	// FieldWaitStart holds the string denoting the wait_start field in the database.
	FieldWaitStart = "wait_start"
	// FieldSold holds the string denoting the sold field in the database.
	FieldSold = "sold"
	// FieldAppReserved holds the string denoting the app_reserved field in the database.
	FieldAppReserved = "app_reserved"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// Table holds the table name of the mininggoodstock in the database.
	Table = "mining_good_stocks"
)

// Columns holds all SQL columns for mininggoodstock fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldEntID,
	FieldGoodStockID,
	FieldPoolRootUserID,
	FieldPoolGoodUserID,
	FieldTotal,
	FieldSpotQuantity,
	FieldLocked,
	FieldInService,
	FieldWaitStart,
	FieldSold,
	FieldAppReserved,
	FieldState,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/NpoolPlatform/good-middleware/pkg/db/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() uint32
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() uint32
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() uint32
	// DefaultDeletedAt holds the default value on creation for the "deleted_at" field.
	DefaultDeletedAt func() uint32
	// DefaultEntID holds the default value on creation for the "ent_id" field.
	DefaultEntID func() uuid.UUID
	// DefaultGoodStockID holds the default value on creation for the "good_stock_id" field.
	DefaultGoodStockID func() uuid.UUID
	// DefaultPoolRootUserID holds the default value on creation for the "pool_root_user_id" field.
	DefaultPoolRootUserID func() uuid.UUID
	// DefaultPoolGoodUserID holds the default value on creation for the "pool_good_user_id" field.
	DefaultPoolGoodUserID func() uuid.UUID
	// DefaultTotal holds the default value on creation for the "total" field.
	DefaultTotal decimal.Decimal
	// DefaultSpotQuantity holds the default value on creation for the "spot_quantity" field.
	DefaultSpotQuantity decimal.Decimal
	// DefaultLocked holds the default value on creation for the "locked" field.
	DefaultLocked decimal.Decimal
	// DefaultInService holds the default value on creation for the "in_service" field.
	DefaultInService decimal.Decimal
	// DefaultWaitStart holds the default value on creation for the "wait_start" field.
	DefaultWaitStart decimal.Decimal
	// DefaultSold holds the default value on creation for the "sold" field.
	DefaultSold decimal.Decimal
	// DefaultAppReserved holds the default value on creation for the "app_reserved" field.
	DefaultAppReserved decimal.Decimal
	// DefaultState holds the default value on creation for the "state" field.
	DefaultState string
)
