// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/good-middleware/pkg/db/ent/apppledge"
	"github.com/NpoolPlatform/good-middleware/pkg/db/ent/predicate"
)

// AppPledgeQuery is the builder for querying AppPledge entities.
type AppPledgeQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.AppPledge
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AppPledgeQuery builder.
func (apq *AppPledgeQuery) Where(ps ...predicate.AppPledge) *AppPledgeQuery {
	apq.predicates = append(apq.predicates, ps...)
	return apq
}

// Limit adds a limit step to the query.
func (apq *AppPledgeQuery) Limit(limit int) *AppPledgeQuery {
	apq.limit = &limit
	return apq
}

// Offset adds an offset step to the query.
func (apq *AppPledgeQuery) Offset(offset int) *AppPledgeQuery {
	apq.offset = &offset
	return apq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (apq *AppPledgeQuery) Unique(unique bool) *AppPledgeQuery {
	apq.unique = &unique
	return apq
}

// Order adds an order step to the query.
func (apq *AppPledgeQuery) Order(o ...OrderFunc) *AppPledgeQuery {
	apq.order = append(apq.order, o...)
	return apq
}

// First returns the first AppPledge entity from the query.
// Returns a *NotFoundError when no AppPledge was found.
func (apq *AppPledgeQuery) First(ctx context.Context) (*AppPledge, error) {
	nodes, err := apq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{apppledge.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (apq *AppPledgeQuery) FirstX(ctx context.Context) *AppPledge {
	node, err := apq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AppPledge ID from the query.
// Returns a *NotFoundError when no AppPledge ID was found.
func (apq *AppPledgeQuery) FirstID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = apq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{apppledge.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (apq *AppPledgeQuery) FirstIDX(ctx context.Context) uint32 {
	id, err := apq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AppPledge entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AppPledge entity is found.
// Returns a *NotFoundError when no AppPledge entities are found.
func (apq *AppPledgeQuery) Only(ctx context.Context) (*AppPledge, error) {
	nodes, err := apq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{apppledge.Label}
	default:
		return nil, &NotSingularError{apppledge.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (apq *AppPledgeQuery) OnlyX(ctx context.Context) *AppPledge {
	node, err := apq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AppPledge ID in the query.
// Returns a *NotSingularError when more than one AppPledge ID is found.
// Returns a *NotFoundError when no entities are found.
func (apq *AppPledgeQuery) OnlyID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = apq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{apppledge.Label}
	default:
		err = &NotSingularError{apppledge.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (apq *AppPledgeQuery) OnlyIDX(ctx context.Context) uint32 {
	id, err := apq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AppPledges.
func (apq *AppPledgeQuery) All(ctx context.Context) ([]*AppPledge, error) {
	if err := apq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return apq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (apq *AppPledgeQuery) AllX(ctx context.Context) []*AppPledge {
	nodes, err := apq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AppPledge IDs.
func (apq *AppPledgeQuery) IDs(ctx context.Context) ([]uint32, error) {
	var ids []uint32
	if err := apq.Select(apppledge.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (apq *AppPledgeQuery) IDsX(ctx context.Context) []uint32 {
	ids, err := apq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (apq *AppPledgeQuery) Count(ctx context.Context) (int, error) {
	if err := apq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return apq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (apq *AppPledgeQuery) CountX(ctx context.Context) int {
	count, err := apq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (apq *AppPledgeQuery) Exist(ctx context.Context) (bool, error) {
	if err := apq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return apq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (apq *AppPledgeQuery) ExistX(ctx context.Context) bool {
	exist, err := apq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AppPledgeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (apq *AppPledgeQuery) Clone() *AppPledgeQuery {
	if apq == nil {
		return nil
	}
	return &AppPledgeQuery{
		config:     apq.config,
		limit:      apq.limit,
		offset:     apq.offset,
		order:      append([]OrderFunc{}, apq.order...),
		predicates: append([]predicate.AppPledge{}, apq.predicates...),
		// clone intermediate query.
		sql:    apq.sql.Clone(),
		path:   apq.path,
		unique: apq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AppPledge.Query().
//		GroupBy(apppledge.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (apq *AppPledgeQuery) GroupBy(field string, fields ...string) *AppPledgeGroupBy {
	grbuild := &AppPledgeGroupBy{config: apq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := apq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return apq.sqlQuery(ctx), nil
	}
	grbuild.label = apppledge.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//	}
//
//	client.AppPledge.Query().
//		Select(apppledge.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (apq *AppPledgeQuery) Select(fields ...string) *AppPledgeSelect {
	apq.fields = append(apq.fields, fields...)
	selbuild := &AppPledgeSelect{AppPledgeQuery: apq}
	selbuild.label = apppledge.Label
	selbuild.flds, selbuild.scan = &apq.fields, selbuild.Scan
	return selbuild
}

func (apq *AppPledgeQuery) prepareQuery(ctx context.Context) error {
	for _, f := range apq.fields {
		if !apppledge.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if apq.path != nil {
		prev, err := apq.path(ctx)
		if err != nil {
			return err
		}
		apq.sql = prev
	}
	if apppledge.Policy == nil {
		return errors.New("ent: uninitialized apppledge.Policy (forgotten import ent/runtime?)")
	}
	if err := apppledge.Policy.EvalQuery(ctx, apq); err != nil {
		return err
	}
	return nil
}

func (apq *AppPledgeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AppPledge, error) {
	var (
		nodes = []*AppPledge{}
		_spec = apq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*AppPledge).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &AppPledge{config: apq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(apq.modifiers) > 0 {
		_spec.Modifiers = apq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, apq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (apq *AppPledgeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := apq.querySpec()
	if len(apq.modifiers) > 0 {
		_spec.Modifiers = apq.modifiers
	}
	_spec.Node.Columns = apq.fields
	if len(apq.fields) > 0 {
		_spec.Unique = apq.unique != nil && *apq.unique
	}
	return sqlgraph.CountNodes(ctx, apq.driver, _spec)
}

func (apq *AppPledgeQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := apq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (apq *AppPledgeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   apppledge.Table,
			Columns: apppledge.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: apppledge.FieldID,
			},
		},
		From:   apq.sql,
		Unique: true,
	}
	if unique := apq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := apq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apppledge.FieldID)
		for i := range fields {
			if fields[i] != apppledge.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := apq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := apq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := apq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := apq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (apq *AppPledgeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(apq.driver.Dialect())
	t1 := builder.Table(apppledge.Table)
	columns := apq.fields
	if len(columns) == 0 {
		columns = apppledge.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if apq.sql != nil {
		selector = apq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if apq.unique != nil && *apq.unique {
		selector.Distinct()
	}
	for _, m := range apq.modifiers {
		m(selector)
	}
	for _, p := range apq.predicates {
		p(selector)
	}
	for _, p := range apq.order {
		p(selector)
	}
	if offset := apq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := apq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (apq *AppPledgeQuery) ForUpdate(opts ...sql.LockOption) *AppPledgeQuery {
	if apq.driver.Dialect() == dialect.Postgres {
		apq.Unique(false)
	}
	apq.modifiers = append(apq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return apq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (apq *AppPledgeQuery) ForShare(opts ...sql.LockOption) *AppPledgeQuery {
	if apq.driver.Dialect() == dialect.Postgres {
		apq.Unique(false)
	}
	apq.modifiers = append(apq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return apq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (apq *AppPledgeQuery) Modify(modifiers ...func(s *sql.Selector)) *AppPledgeSelect {
	apq.modifiers = append(apq.modifiers, modifiers...)
	return apq.Select()
}

// AppPledgeGroupBy is the group-by builder for AppPledge entities.
type AppPledgeGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (apgb *AppPledgeGroupBy) Aggregate(fns ...AggregateFunc) *AppPledgeGroupBy {
	apgb.fns = append(apgb.fns, fns...)
	return apgb
}

// Scan applies the group-by query and scans the result into the given value.
func (apgb *AppPledgeGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := apgb.path(ctx)
	if err != nil {
		return err
	}
	apgb.sql = query
	return apgb.sqlScan(ctx, v)
}

func (apgb *AppPledgeGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range apgb.fields {
		if !apppledge.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := apgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := apgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (apgb *AppPledgeGroupBy) sqlQuery() *sql.Selector {
	selector := apgb.sql.Select()
	aggregation := make([]string, 0, len(apgb.fns))
	for _, fn := range apgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(apgb.fields)+len(apgb.fns))
		for _, f := range apgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(apgb.fields...)...)
}

// AppPledgeSelect is the builder for selecting fields of AppPledge entities.
type AppPledgeSelect struct {
	*AppPledgeQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (aps *AppPledgeSelect) Scan(ctx context.Context, v interface{}) error {
	if err := aps.prepareQuery(ctx); err != nil {
		return err
	}
	aps.sql = aps.AppPledgeQuery.sqlQuery(ctx)
	return aps.sqlScan(ctx, v)
}

func (aps *AppPledgeSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := aps.sql.Query()
	if err := aps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (aps *AppPledgeSelect) Modify(modifiers ...func(s *sql.Selector)) *AppPledgeSelect {
	aps.modifiers = append(aps.modifiers, modifiers...)
	return aps
}
