// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/good-middleware/pkg/db/ent/delegatedstaking"
	"github.com/NpoolPlatform/good-middleware/pkg/db/ent/predicate"
)

// DelegatedStakingQuery is the builder for querying DelegatedStaking entities.
type DelegatedStakingQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.DelegatedStaking
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DelegatedStakingQuery builder.
func (dsq *DelegatedStakingQuery) Where(ps ...predicate.DelegatedStaking) *DelegatedStakingQuery {
	dsq.predicates = append(dsq.predicates, ps...)
	return dsq
}

// Limit adds a limit step to the query.
func (dsq *DelegatedStakingQuery) Limit(limit int) *DelegatedStakingQuery {
	dsq.limit = &limit
	return dsq
}

// Offset adds an offset step to the query.
func (dsq *DelegatedStakingQuery) Offset(offset int) *DelegatedStakingQuery {
	dsq.offset = &offset
	return dsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (dsq *DelegatedStakingQuery) Unique(unique bool) *DelegatedStakingQuery {
	dsq.unique = &unique
	return dsq
}

// Order adds an order step to the query.
func (dsq *DelegatedStakingQuery) Order(o ...OrderFunc) *DelegatedStakingQuery {
	dsq.order = append(dsq.order, o...)
	return dsq
}

// First returns the first DelegatedStaking entity from the query.
// Returns a *NotFoundError when no DelegatedStaking was found.
func (dsq *DelegatedStakingQuery) First(ctx context.Context) (*DelegatedStaking, error) {
	nodes, err := dsq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{delegatedstaking.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (dsq *DelegatedStakingQuery) FirstX(ctx context.Context) *DelegatedStaking {
	node, err := dsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DelegatedStaking ID from the query.
// Returns a *NotFoundError when no DelegatedStaking ID was found.
func (dsq *DelegatedStakingQuery) FirstID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = dsq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{delegatedstaking.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (dsq *DelegatedStakingQuery) FirstIDX(ctx context.Context) uint32 {
	id, err := dsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DelegatedStaking entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DelegatedStaking entity is found.
// Returns a *NotFoundError when no DelegatedStaking entities are found.
func (dsq *DelegatedStakingQuery) Only(ctx context.Context) (*DelegatedStaking, error) {
	nodes, err := dsq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{delegatedstaking.Label}
	default:
		return nil, &NotSingularError{delegatedstaking.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (dsq *DelegatedStakingQuery) OnlyX(ctx context.Context) *DelegatedStaking {
	node, err := dsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DelegatedStaking ID in the query.
// Returns a *NotSingularError when more than one DelegatedStaking ID is found.
// Returns a *NotFoundError when no entities are found.
func (dsq *DelegatedStakingQuery) OnlyID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = dsq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{delegatedstaking.Label}
	default:
		err = &NotSingularError{delegatedstaking.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (dsq *DelegatedStakingQuery) OnlyIDX(ctx context.Context) uint32 {
	id, err := dsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DelegatedStakings.
func (dsq *DelegatedStakingQuery) All(ctx context.Context) ([]*DelegatedStaking, error) {
	if err := dsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return dsq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (dsq *DelegatedStakingQuery) AllX(ctx context.Context) []*DelegatedStaking {
	nodes, err := dsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DelegatedStaking IDs.
func (dsq *DelegatedStakingQuery) IDs(ctx context.Context) ([]uint32, error) {
	var ids []uint32
	if err := dsq.Select(delegatedstaking.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (dsq *DelegatedStakingQuery) IDsX(ctx context.Context) []uint32 {
	ids, err := dsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (dsq *DelegatedStakingQuery) Count(ctx context.Context) (int, error) {
	if err := dsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return dsq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (dsq *DelegatedStakingQuery) CountX(ctx context.Context) int {
	count, err := dsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (dsq *DelegatedStakingQuery) Exist(ctx context.Context) (bool, error) {
	if err := dsq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return dsq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (dsq *DelegatedStakingQuery) ExistX(ctx context.Context) bool {
	exist, err := dsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DelegatedStakingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (dsq *DelegatedStakingQuery) Clone() *DelegatedStakingQuery {
	if dsq == nil {
		return nil
	}
	return &DelegatedStakingQuery{
		config:     dsq.config,
		limit:      dsq.limit,
		offset:     dsq.offset,
		order:      append([]OrderFunc{}, dsq.order...),
		predicates: append([]predicate.DelegatedStaking{}, dsq.predicates...),
		// clone intermediate query.
		sql:    dsq.sql.Clone(),
		path:   dsq.path,
		unique: dsq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DelegatedStaking.Query().
//		GroupBy(delegatedstaking.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (dsq *DelegatedStakingQuery) GroupBy(field string, fields ...string) *DelegatedStakingGroupBy {
	grbuild := &DelegatedStakingGroupBy{config: dsq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := dsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return dsq.sqlQuery(ctx), nil
	}
	grbuild.label = delegatedstaking.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//	}
//
//	client.DelegatedStaking.Query().
//		Select(delegatedstaking.FieldCreatedAt).
//		Scan(ctx, &v)
func (dsq *DelegatedStakingQuery) Select(fields ...string) *DelegatedStakingSelect {
	dsq.fields = append(dsq.fields, fields...)
	selbuild := &DelegatedStakingSelect{DelegatedStakingQuery: dsq}
	selbuild.label = delegatedstaking.Label
	selbuild.flds, selbuild.scan = &dsq.fields, selbuild.Scan
	return selbuild
}

func (dsq *DelegatedStakingQuery) prepareQuery(ctx context.Context) error {
	for _, f := range dsq.fields {
		if !delegatedstaking.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if dsq.path != nil {
		prev, err := dsq.path(ctx)
		if err != nil {
			return err
		}
		dsq.sql = prev
	}
	if delegatedstaking.Policy == nil {
		return errors.New("ent: uninitialized delegatedstaking.Policy (forgotten import ent/runtime?)")
	}
	if err := delegatedstaking.Policy.EvalQuery(ctx, dsq); err != nil {
		return err
	}
	return nil
}

func (dsq *DelegatedStakingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DelegatedStaking, error) {
	var (
		nodes = []*DelegatedStaking{}
		_spec = dsq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*DelegatedStaking).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &DelegatedStaking{config: dsq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(dsq.modifiers) > 0 {
		_spec.Modifiers = dsq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, dsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (dsq *DelegatedStakingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := dsq.querySpec()
	if len(dsq.modifiers) > 0 {
		_spec.Modifiers = dsq.modifiers
	}
	_spec.Node.Columns = dsq.fields
	if len(dsq.fields) > 0 {
		_spec.Unique = dsq.unique != nil && *dsq.unique
	}
	return sqlgraph.CountNodes(ctx, dsq.driver, _spec)
}

func (dsq *DelegatedStakingQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := dsq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (dsq *DelegatedStakingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   delegatedstaking.Table,
			Columns: delegatedstaking.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: delegatedstaking.FieldID,
			},
		},
		From:   dsq.sql,
		Unique: true,
	}
	if unique := dsq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := dsq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, delegatedstaking.FieldID)
		for i := range fields {
			if fields[i] != delegatedstaking.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := dsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := dsq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := dsq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := dsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (dsq *DelegatedStakingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(dsq.driver.Dialect())
	t1 := builder.Table(delegatedstaking.Table)
	columns := dsq.fields
	if len(columns) == 0 {
		columns = delegatedstaking.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if dsq.sql != nil {
		selector = dsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if dsq.unique != nil && *dsq.unique {
		selector.Distinct()
	}
	for _, m := range dsq.modifiers {
		m(selector)
	}
	for _, p := range dsq.predicates {
		p(selector)
	}
	for _, p := range dsq.order {
		p(selector)
	}
	if offset := dsq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := dsq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (dsq *DelegatedStakingQuery) ForUpdate(opts ...sql.LockOption) *DelegatedStakingQuery {
	if dsq.driver.Dialect() == dialect.Postgres {
		dsq.Unique(false)
	}
	dsq.modifiers = append(dsq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return dsq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (dsq *DelegatedStakingQuery) ForShare(opts ...sql.LockOption) *DelegatedStakingQuery {
	if dsq.driver.Dialect() == dialect.Postgres {
		dsq.Unique(false)
	}
	dsq.modifiers = append(dsq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return dsq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (dsq *DelegatedStakingQuery) Modify(modifiers ...func(s *sql.Selector)) *DelegatedStakingSelect {
	dsq.modifiers = append(dsq.modifiers, modifiers...)
	return dsq.Select()
}

// DelegatedStakingGroupBy is the group-by builder for DelegatedStaking entities.
type DelegatedStakingGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (dsgb *DelegatedStakingGroupBy) Aggregate(fns ...AggregateFunc) *DelegatedStakingGroupBy {
	dsgb.fns = append(dsgb.fns, fns...)
	return dsgb
}

// Scan applies the group-by query and scans the result into the given value.
func (dsgb *DelegatedStakingGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := dsgb.path(ctx)
	if err != nil {
		return err
	}
	dsgb.sql = query
	return dsgb.sqlScan(ctx, v)
}

func (dsgb *DelegatedStakingGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range dsgb.fields {
		if !delegatedstaking.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := dsgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dsgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (dsgb *DelegatedStakingGroupBy) sqlQuery() *sql.Selector {
	selector := dsgb.sql.Select()
	aggregation := make([]string, 0, len(dsgb.fns))
	for _, fn := range dsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(dsgb.fields)+len(dsgb.fns))
		for _, f := range dsgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(dsgb.fields...)...)
}

// DelegatedStakingSelect is the builder for selecting fields of DelegatedStaking entities.
type DelegatedStakingSelect struct {
	*DelegatedStakingQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (dss *DelegatedStakingSelect) Scan(ctx context.Context, v interface{}) error {
	if err := dss.prepareQuery(ctx); err != nil {
		return err
	}
	dss.sql = dss.DelegatedStakingQuery.sqlQuery(ctx)
	return dss.sqlScan(ctx, v)
}

func (dss *DelegatedStakingSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := dss.sql.Query()
	if err := dss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (dss *DelegatedStakingSelect) Modify(modifiers ...func(s *sql.Selector)) *DelegatedStakingSelect {
	dss.modifiers = append(dss.modifiers, modifiers...)
	return dss
}
