// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/good-middleware/pkg/db/ent/goodrewardhistory"
	"github.com/NpoolPlatform/good-middleware/pkg/db/ent/predicate"
)

// GoodRewardHistoryDelete is the builder for deleting a GoodRewardHistory entity.
type GoodRewardHistoryDelete struct {
	config
	hooks    []Hook
	mutation *GoodRewardHistoryMutation
}

// Where appends a list predicates to the GoodRewardHistoryDelete builder.
func (grhd *GoodRewardHistoryDelete) Where(ps ...predicate.GoodRewardHistory) *GoodRewardHistoryDelete {
	grhd.mutation.Where(ps...)
	return grhd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (grhd *GoodRewardHistoryDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(grhd.hooks) == 0 {
		affected, err = grhd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GoodRewardHistoryMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			grhd.mutation = mutation
			affected, err = grhd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(grhd.hooks) - 1; i >= 0; i-- {
			if grhd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = grhd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, grhd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (grhd *GoodRewardHistoryDelete) ExecX(ctx context.Context) int {
	n, err := grhd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (grhd *GoodRewardHistoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: goodrewardhistory.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: goodrewardhistory.FieldID,
			},
		},
	}
	if ps := grhd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, grhd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// GoodRewardHistoryDeleteOne is the builder for deleting a single GoodRewardHistory entity.
type GoodRewardHistoryDeleteOne struct {
	grhd *GoodRewardHistoryDelete
}

// Exec executes the deletion query.
func (grhdo *GoodRewardHistoryDeleteOne) Exec(ctx context.Context) error {
	n, err := grhdo.grhd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{goodrewardhistory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (grhdo *GoodRewardHistoryDeleteOne) ExecX(ctx context.Context) {
	grhdo.grhd.ExecX(ctx)
}
