// Code generated by ent, DO NOT EDIT.

package appfee

import (
	"entgo.io/ent/dialect/sql"
	"github.com/NpoolPlatform/good-middleware/pkg/db/ent/predicate"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDeletedAt), v))
	})
}

// EntID applies equality check predicate on the "ent_id" field. It's identical to EntIDEQ.
func EntID(v uuid.UUID) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldEntID), v))
	})
}

// AppID applies equality check predicate on the "app_id" field. It's identical to AppIDEQ.
func AppID(v uuid.UUID) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAppID), v))
	})
}

// GoodID applies equality check predicate on the "good_id" field. It's identical to GoodIDEQ.
func GoodID(v uuid.UUID) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldGoodID), v))
	})
}

// UnitValue applies equality check predicate on the "unit_value" field. It's identical to UnitValueEQ.
func UnitValue(v decimal.Decimal) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUnitValue), v))
	})
}

// MinOrderDuration applies equality check predicate on the "min_order_duration" field. It's identical to MinOrderDurationEQ.
func MinOrderDuration(v uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldMinOrderDuration), v))
	})
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...uint32) predicate.AppFee {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...uint32) predicate.AppFee {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...uint32) predicate.AppFee {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...uint32) predicate.AppFee {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUpdatedAt), v))
	})
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...uint32) predicate.AppFee {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldDeletedAt), v...))
	})
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...uint32) predicate.AppFee {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldDeletedAt), v...))
	})
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDeletedAt), v))
	})
}

// EntIDEQ applies the EQ predicate on the "ent_id" field.
func EntIDEQ(v uuid.UUID) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldEntID), v))
	})
}

// EntIDNEQ applies the NEQ predicate on the "ent_id" field.
func EntIDNEQ(v uuid.UUID) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldEntID), v))
	})
}

// EntIDIn applies the In predicate on the "ent_id" field.
func EntIDIn(vs ...uuid.UUID) predicate.AppFee {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldEntID), v...))
	})
}

// EntIDNotIn applies the NotIn predicate on the "ent_id" field.
func EntIDNotIn(vs ...uuid.UUID) predicate.AppFee {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldEntID), v...))
	})
}

// EntIDGT applies the GT predicate on the "ent_id" field.
func EntIDGT(v uuid.UUID) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldEntID), v))
	})
}

// EntIDGTE applies the GTE predicate on the "ent_id" field.
func EntIDGTE(v uuid.UUID) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldEntID), v))
	})
}

// EntIDLT applies the LT predicate on the "ent_id" field.
func EntIDLT(v uuid.UUID) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldEntID), v))
	})
}

// EntIDLTE applies the LTE predicate on the "ent_id" field.
func EntIDLTE(v uuid.UUID) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldEntID), v))
	})
}

// AppIDEQ applies the EQ predicate on the "app_id" field.
func AppIDEQ(v uuid.UUID) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAppID), v))
	})
}

// AppIDNEQ applies the NEQ predicate on the "app_id" field.
func AppIDNEQ(v uuid.UUID) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldAppID), v))
	})
}

// AppIDIn applies the In predicate on the "app_id" field.
func AppIDIn(vs ...uuid.UUID) predicate.AppFee {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldAppID), v...))
	})
}

// AppIDNotIn applies the NotIn predicate on the "app_id" field.
func AppIDNotIn(vs ...uuid.UUID) predicate.AppFee {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldAppID), v...))
	})
}

// AppIDGT applies the GT predicate on the "app_id" field.
func AppIDGT(v uuid.UUID) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldAppID), v))
	})
}

// AppIDGTE applies the GTE predicate on the "app_id" field.
func AppIDGTE(v uuid.UUID) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldAppID), v))
	})
}

// AppIDLT applies the LT predicate on the "app_id" field.
func AppIDLT(v uuid.UUID) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldAppID), v))
	})
}

// AppIDLTE applies the LTE predicate on the "app_id" field.
func AppIDLTE(v uuid.UUID) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldAppID), v))
	})
}

// AppIDIsNil applies the IsNil predicate on the "app_id" field.
func AppIDIsNil() predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldAppID)))
	})
}

// AppIDNotNil applies the NotNil predicate on the "app_id" field.
func AppIDNotNil() predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldAppID)))
	})
}

// GoodIDEQ applies the EQ predicate on the "good_id" field.
func GoodIDEQ(v uuid.UUID) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldGoodID), v))
	})
}

// GoodIDNEQ applies the NEQ predicate on the "good_id" field.
func GoodIDNEQ(v uuid.UUID) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldGoodID), v))
	})
}

// GoodIDIn applies the In predicate on the "good_id" field.
func GoodIDIn(vs ...uuid.UUID) predicate.AppFee {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldGoodID), v...))
	})
}

// GoodIDNotIn applies the NotIn predicate on the "good_id" field.
func GoodIDNotIn(vs ...uuid.UUID) predicate.AppFee {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldGoodID), v...))
	})
}

// GoodIDGT applies the GT predicate on the "good_id" field.
func GoodIDGT(v uuid.UUID) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldGoodID), v))
	})
}

// GoodIDGTE applies the GTE predicate on the "good_id" field.
func GoodIDGTE(v uuid.UUID) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldGoodID), v))
	})
}

// GoodIDLT applies the LT predicate on the "good_id" field.
func GoodIDLT(v uuid.UUID) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldGoodID), v))
	})
}

// GoodIDLTE applies the LTE predicate on the "good_id" field.
func GoodIDLTE(v uuid.UUID) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldGoodID), v))
	})
}

// GoodIDIsNil applies the IsNil predicate on the "good_id" field.
func GoodIDIsNil() predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldGoodID)))
	})
}

// GoodIDNotNil applies the NotNil predicate on the "good_id" field.
func GoodIDNotNil() predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldGoodID)))
	})
}

// UnitValueEQ applies the EQ predicate on the "unit_value" field.
func UnitValueEQ(v decimal.Decimal) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUnitValue), v))
	})
}

// UnitValueNEQ applies the NEQ predicate on the "unit_value" field.
func UnitValueNEQ(v decimal.Decimal) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUnitValue), v))
	})
}

// UnitValueIn applies the In predicate on the "unit_value" field.
func UnitValueIn(vs ...decimal.Decimal) predicate.AppFee {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldUnitValue), v...))
	})
}

// UnitValueNotIn applies the NotIn predicate on the "unit_value" field.
func UnitValueNotIn(vs ...decimal.Decimal) predicate.AppFee {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldUnitValue), v...))
	})
}

// UnitValueGT applies the GT predicate on the "unit_value" field.
func UnitValueGT(v decimal.Decimal) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUnitValue), v))
	})
}

// UnitValueGTE applies the GTE predicate on the "unit_value" field.
func UnitValueGTE(v decimal.Decimal) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUnitValue), v))
	})
}

// UnitValueLT applies the LT predicate on the "unit_value" field.
func UnitValueLT(v decimal.Decimal) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUnitValue), v))
	})
}

// UnitValueLTE applies the LTE predicate on the "unit_value" field.
func UnitValueLTE(v decimal.Decimal) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUnitValue), v))
	})
}

// UnitValueIsNil applies the IsNil predicate on the "unit_value" field.
func UnitValueIsNil() predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldUnitValue)))
	})
}

// UnitValueNotNil applies the NotNil predicate on the "unit_value" field.
func UnitValueNotNil() predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldUnitValue)))
	})
}

// MinOrderDurationEQ applies the EQ predicate on the "min_order_duration" field.
func MinOrderDurationEQ(v uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldMinOrderDuration), v))
	})
}

// MinOrderDurationNEQ applies the NEQ predicate on the "min_order_duration" field.
func MinOrderDurationNEQ(v uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldMinOrderDuration), v))
	})
}

// MinOrderDurationIn applies the In predicate on the "min_order_duration" field.
func MinOrderDurationIn(vs ...uint32) predicate.AppFee {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldMinOrderDuration), v...))
	})
}

// MinOrderDurationNotIn applies the NotIn predicate on the "min_order_duration" field.
func MinOrderDurationNotIn(vs ...uint32) predicate.AppFee {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldMinOrderDuration), v...))
	})
}

// MinOrderDurationGT applies the GT predicate on the "min_order_duration" field.
func MinOrderDurationGT(v uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldMinOrderDuration), v))
	})
}

// MinOrderDurationGTE applies the GTE predicate on the "min_order_duration" field.
func MinOrderDurationGTE(v uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldMinOrderDuration), v))
	})
}

// MinOrderDurationLT applies the LT predicate on the "min_order_duration" field.
func MinOrderDurationLT(v uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldMinOrderDuration), v))
	})
}

// MinOrderDurationLTE applies the LTE predicate on the "min_order_duration" field.
func MinOrderDurationLTE(v uint32) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldMinOrderDuration), v))
	})
}

// MinOrderDurationIsNil applies the IsNil predicate on the "min_order_duration" field.
func MinOrderDurationIsNil() predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldMinOrderDuration)))
	})
}

// MinOrderDurationNotNil applies the NotNil predicate on the "min_order_duration" field.
func MinOrderDurationNotNil() predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldMinOrderDuration)))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AppFee) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AppFee) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AppFee) predicate.AppFee {
	return predicate.AppFee(func(s *sql.Selector) {
		p(s.Not())
	})
}
