apiVersion: v1
kind: ConfigMap
metadata:
  name: good-middleware-config
  namespace: kube-system
data:
  service-conf: |
    config:
      hostname: "good-middleware.npool.top"
      http_port: 50530
      grpc_port: 50531
      healthz_port: 50532
      prometheus_port: 50533
      appid: "89089012783789789719823798127398"
      serviceid: "91e32436-4894-11ed-905a-72e9de4b20f6"
      logdir: "./"
      apolloAccessKey: "0147fb70b815403790e8634b899fac07"
